travis:
  secure:
    BINSTAR_TOKEN: b/JOtLloMAGqYR9j9krSu6gxTfVg9Ldt58EOV1rx2EOrlC+FeWpNf4h8RnRT/HBiPwWT1ijt+G3Vw6UTz8PWHs5Gf9jLHtjb5H+QnH/mAbsrnTCDaSGBEsiuvx1TaD+9HyR3WWgA4uyRca0jBu7rBpQIWdfAKMEzpAVyFxf9noR/1xY32tmx0vLxviiLCyaPb07wKatqtBlgRo5fl3I+BHGxRSjP+tI5o95Zcv1oBkUai4roF9T8yG0AXF6zTbprE0IABp4SZzQfXNi65fRDEglHSNnyM+CAnsTJy6Vm3lB+WtXcHbuxOuSbEdAl6YBiHEfK+cXL2/HV4UvIFDwsblwjzr6Gwb+8FMFI9kvtVRmlXZMR592SYiX9hKkwNkVrTn7e5jUQa198WP4HcbUHWEkxAmaB25svPn+2GKUlug2PK+6Y8lQHUD6sy6URvhVd3RhTK+fikXEnLrT5BDaHG8g8Cq3b5C2oGuHHwIgwmIS+lXsJX2PPhvZz9pQmDwllbQeQeUDzW7e+7RIhSJVHWzfPzJ6rw7D4n3id1H9L9x8Mp4a2GgHMDvC3SEOD+cgJE1Dis88F+4XeDwxVPifeKZogDMknF2zZ0/2nKtwQ6UYOK2zjt6RB7tOfL+nfW+FEtIQhGtbuqUb+wIvW4ES/9Y0l8lYU8ew2lRshSt+sfeY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
